### ISSUE TITLE
Request to add a messages file

### ISSUE THREAD

**Issue by dutchy1001** [KeepJ96/IP-Check#14]
Is it possible to add a messages file so non English servers can translate according to their own language?

**Comment by KeepJ96** [comment]
Support for this is already a feature of IP-Check as of version 1.4.0. At this time, however, there is no 'en.yml' as it is already hard-coded into the plugin. I can look at making this a separate file for 2.0.8.

**Comment by KeepJ96** [comment]
We could also potentially look into making this either a hard coded feature of the plugin for all supported languages, or making a "translation library." which could be downloaded separately and would contain all supported languages. The only problem is that this would need to be updated every time a new build was released.
