### ISSUE TITLE
Error in config

### ISSUE THREAD

**Issue by Heron4gf** [KeepJ96/IP-Check#23]
I want to setup this config in the way i have as whitelist only italy and switzerland

language: en
use-mysql: false
dbUsername: root
dbPassword: ''
dbHostname: 127.0.0.1
dbName: ip-check
dbPort: 3306
dbGenerated: true
notify-on-login: true
warn-on-rejoin-attempt: false
descriptive-notice: false
secure-mode: false
should-manage-bans: true
active-mode: false
should-ban-on-secure-kick: false
min-account-notify-threshold: 1
secure-kick-threshold: 1
secure-kick-message: Multiple Accounts Not Permitted.
ban-message: Banned for Multi-Accounting.
kick-message: Kicked from server.
disable-update-detection: false
disable-metrics-monitoring: false
use-geoip-services: true
allow-geoip-download: true
use-country-blacklist: true
use-blacklist-as-whitelist: false
country-blacklist: []
blocked-message: Your country has been blocked from joining this server.
config-version: 5

**Comment by KeepJ96** [comment]
Set 'use-blacklist-as-whitelist' to true, then add 'CH' (Switzerland) and 'IT' (Italy) to the country blacklist.

**Comment by Heron4gf** [comment]
Yes but in what format?
Thing:
- thing


Or thing: ['thing']

Il Ven 19 Lug 2019, 14:19 Jnk1296 <notifications@github.com> ha scritto:

**Comment by KeepJ96** [comment]
Honestly, I don't remember, as I haven't actively done anything with this plugin in several years.

My recommendation would be to add the exemptions from in-game/console, using the commands **'/ipc block ch'** and **'/ipc block it'** respectively. This will add them to the list, which will function as a whitelist given that 'use-blacklist-as-whitelist' is true.

**Comment by Heron4gf** [comment]
Ok thank you

Il Ven 19 Lug 2019, 14:41 Jnk1296 <notifications@github.com> ha scritto:
